name: Build and publish PHP binaries

on:
  push:
    branches: "**"
    tags-ignore: "php-**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  all-builds:
    name: PM${{ matrix.pm-version-major }} - PHP ${{ matrix.php-version-base }}
    strategy:
      matrix:
        include:
          - pm-version-major: 5
            php-version-base: "8.2"
            special-release: default-latest #default = best for PM5, latest = display as latest on GitHub 
          - pm-version-major: 5
            php-version-base: "8.3"
            special-release: none

    uses: ./.github/workflows/main-pm-matrix.yml
    with:
      pm-version-major: ${{ matrix.pm-version-major }}
      php-version-base: ${{ matrix.php-version-base }}
      special-release: ${{ matrix.special-release }}
      pm-preview: ${{ matrix.pm-preview || false }}
    secrets: inherit
