name: Build and publish PHP binaries

on:
  push:
    branches: "**"
    tags-ignore: "php-**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  all-builds:
    name: PM${{ matrix.pm-version-major }} - PHP ${{ inputs.php-version-base }}
    strategy:
      matrix:
        pm-version-major: [5]
        php-version-base: ["8.2", "8.3"]

    uses: ./.github/workflows/main-pm-matrix.yml
    with:
      pm-version-major: ${{ matrix.pm-version-major }}
      php-version-base: ${{ matrix.php-version-base }}
    secrets: inherit
